### ISSUE TITLE
Cập nhật link Colab và file kế hoạch phân chia công việc nhóm

### ISSUE THREAD

**Issue by KienTrann** [TranNgocTinh0810/Global-Wheat-Detection#1]
Hiện giờ trong file README.md mình chưa thấy link Colab để mở file notebook. Còn file kế hoạch phân chia công việc nhóm thì mình thấy chưa rõ: mình nhìn vào thì mình không biết trong tuần này các thành viên trong nhóm đang làm gì. Có gì tụi em cập nhật lại nha.

**Comment by TranNgocTinh0810** [comment]
Dạ vâng ạ. Nhóm em sẽ sớm cập nhật các phần.
